### ISSUE TITLE
Создание документации проекта

### ISSUE THREAD

**Issue by WrapAndKit** [TeamSnail/HamsterJourney#11]
# Coding

- [x] Code Review Guideline
- [x] Code Issue List

# Design

- [ ] Game Design Document
- [ ] Software Design Specification

# Project Plan

- [x] Software Project Plan
- [ ] Task State Model
- [ ] Issue Creation Guideline

# Requirements

- [x] Marketing Requirements Specification
- [x] Software Requirements Specification
- [ ] User Manual

# Testing

- [x] Metrics
- [x] Software Test Plan
- [ ] Test Traceability Matrix
- [ ] Test Logs
- [ ] Requirements Traceability Matrix
